name: Install with flit and test via Pytest

on:
  push:
    paths:
    - '**.py' # only run workflow when source files changed

jobs:
  linux-pytest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      
    - name: Check Black code style
      uses: psf/black@stable #https://black.readthedocs.io/en/stable/integrations/github_actions.html
    
    - name: Upgrade pip
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install flit pytest
        flit install
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        export NUMBA_ENABLE_CUDASIM="1"
        python -m pytest
